---
name: Scheduled Release

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build
        required: false
        type: string
        default: all
      force:
        description: Force rebuild
        type: boolean
        default: false
        required: true
  schedule:
    - cron: "0 * * * *"

jobs:
  simple-checks:
    name: Simple Checks
    uses: JJGadgets/containers/.github/workflows/simple-checks.yaml@c4234b04ecc61bf9e64365d2d5031d48e595c7bc # main

  build-images:
    name: Build Images
    needs: simple-checks
    uses: JJGadgets/containers/.github/workflows/build-images.yaml@c4234b04ecc61bf9e64365d2d5031d48e595c7bc # main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      appsToBuild: ${{ inputs.appsToBuild }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    uses: JJGadgets/containers/.github/workflows/render-readme.yaml@c4234b04ecc61bf9e64365d2d5031d48e595c7bc # main
    secrets: inherit
