---
name: Scheduled Release

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build
        required: false
        type: string
        default: all
      force:
        description: Force rebuild
        type: boolean
        default: false
        required: true
  schedule:
    - cron: "0 * * * *"

jobs:
  simple-checks:
    name: Simple Checks
    uses: JJGadgets/containers/.github/workflows/simple-checks.yaml@83bcd22a75014b8978ad6dc980dfe6d6605b6564 # main

  build-images:
    name: Build Images
    needs: simple-checks
    uses: JJGadgets/containers/.github/workflows/build-images.yaml@83bcd22a75014b8978ad6dc980dfe6d6605b6564 # main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      appsToBuild: ${{ inputs.appsToBuild }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    uses: JJGadgets/containers/.github/workflows/render-readme.yaml@83bcd22a75014b8978ad6dc980dfe6d6605b6564 # main
    secrets: inherit
